[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "player>=0.6.1",
    "tabulate>=0.9.0",
]
